version: '2'
services:
  filebeat:
    container_name: filebeat
    build:
      context: ./filebeat
      dockerfile: ./Dockerfile
    mem_limit: 128m
    restart: always
    command: filebeat -e -strict.perms=false -path.config /usr/share/filebeat    
    volumes:
      - ../minhaoi-home-backend:/aplicacao
        
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - 5601:5601